### ISSUE TITLE
classdump-dyld Crashing ~half way through dumping app

### ISSUE THREAD

**Issue by Jake0oo0** [limneos/classdump-dyld#14]
Hi,

I'm using classdump-dyld to dump Instagram's headers, and have been for a long time. At some point a couple months ago, I started running into issues where it would dump a certain number of files and then crash. Note that the files are never actually written to the output folder, as if they're just stored in memory and not written until it *successfully* completes, which it doesn't.

Gets to 42% here:

```
iPhone:~ root# classdump-dyld /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram -o ~/out
  Dumping /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram...(3075 classes)  (injected with libclassdumpdyld.dylib) 
 42% [=====================                             ]  1320/3075 <IGStatusBarWindow>
```

Then SSH is disconnected (killed?) 
```
Connection to localhost closed by remote host.
Connection to localhost closed.
```

Not sure what's going on here. It's like Instagram is intentionally causing this to prevent the app from being dumped, but that doesn't sound right.

I can't find a way to enable a verbose mode, so I'm not too sure what's going on behind the scenes. 

I've also tried to inject it into Cycript and run it that way, but I run into similar issues.

Said issue:
```
iPhone:~ root# cycript -p Instagram
cy# dlopen("/usr/lib/libclassdumpdyld.dylib",RTLD_NOW);
(typedef void*)(0x14f02db10)
cy# dumpBundle=@encode(id(id))(dlsym(RTLD_DEFAULT,"dumpBundle"));
(extern "C" id dumpBundle(id))
cy# dumpBundle([NSBundle mainBundle ])
MS:Error: _krncall(mach_vm_read_overwrite(task, data, sizeof(*baton), reinterpret_cast<mach_vm_address_t>(baton), &error)) =4
*** _assert(status == 0):../Inject.cpp(143):InjectLibrary
```

Any help would be appreciated..

iPhone 6s (Happened on i5 as well), iOS 9.0

**Comment by Jake0oo0** [comment]
Just tried to manually dump the header that it was freezing on:

```
iPhone:~ root# classdump-dyld /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram -o ~/out -j IGStatusBarWindow
  Dumping /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram...(3075 classes)  (injected with libclassdumpdyld.dylib) 
 42% [=====================                             ]  1320/3075 <IGStatusBa  Writing /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram headers to disk...
  All done for /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram
  Done. Check "/var/root/out" directory.
```

Works fine and the header is written to the output folder.

Still not sure though..

**Comment by Jake0oo0** [comment]
Okay, I figured out there is actually a way to make it verbose with -D, so I did that...

Relevant log is [here](https://ghostbin.com/paste/fq93j).

Now the odd part is that IGStatusBarWindow is actually being processed, but seemingly not updated in the progress bar. Instead, it's actually freezing up on IGInstaVideoController in the background.

I reran a single class dump on that class:

```
iPhone:~ root# classdump-dyld /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram -o ~/out -j IGInstaVideoController
  Dumping /var/mobile/Containers/Bundle/Application/176992E6-9F75-4A3D-BB05-1C1C6D5676B0/Instagram.app/Instagram...(3075 classes)  (injected with libclassdumpdyld.dylib) 
Connection to localhost closed by remote host.
Connection to localhost closed.
```

It ends up quitting again.. so it's definitely this class that is causing it. I don't believe that it could be an OOM error since it's only dumping one class this time, and the mem. usage is at a normal level.

Is it actually possible that Instagram is doing something to freeze up the process here..?

**Comment by jjjapj** [comment]
The same issue is occurring with the Ticketmaster application.

**Comment by aaronash** [comment]
Curious if anyone found out anything else about this issue?

**Comment by limneos** [comment]
This usually happens either due to memory issues or some class being instantiated and causing this. For some reason I don't recall, classdump-dyld may allocate some classes instead of simply getting their methods,ivars lists, which may cause this error in some applications and with certain classes.
Currently re-writing classdump-dyld to use only c functions and remove any objective-c code, as I noticed its 500-600% faster.  Also, I'll be adding proper swift support.
