### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fattalgazi** [limneos/classdump-dyld#7]
Hello,

when i try to make command, it says : 

Making all for tool classdump-dyld...
make[2]: Nothing to be done for `internal-tool-compile'.
Making all in classdumpdyldlib...
Makefile:1: theos/makefiles/common.mk: No such file or directory
Theos version mismatch! common.mk [version 0] loaded in tandem with rules.mk [version 1] Check that $(THEOS) is set properly!
make[1]: *** [all] Error 1
make: *** [internal-all] Error 2

what can be the problem ? There is  theos/makefiles/common.mk file in folder.

**Comment by exxr** [comment]
You need a symlink to theos in the classdumpdyldlib subfolder also, in addition to the one for the classdump-dyld folder itself.
